---
- name: setup local
  hosts: localhost
  become: true
  vars:
    # For Common
    apex_ver      : '1.0.0-rc3'
    aws_cli_ver   : '1.18.26'
    hugo_ver      : '0.68.2'
    terraform_ver : '0.12.24'

    # For python
    py_plguin_pillow : '7.0.0'
    py_plguin_pyyaml : '5.3.1'
  roles:
    - common
    - python